### PR TITLE
don't crash when handle unsupported content type

### PR DESCRIPTION
**Pull request by amacou**
fix crash when handle gif or other content type

### CODE REVIEW

**Comment by svoboda-jan** [comment]
Hello,

thank you for the pull request.

Unfortunately we cannot add the content type check.

The gem that handles the underlying compression (https://github.com/svoboda-jan/paperclip-mozjpeg) supports PNG format only when using the supplied binaries and only under Mac OS.

This changes when `use_system_binaries` and `mozjpeg_path` are defined and then it depends on the specific version and OS in use.

I recommend using paperclip validations like `validates_attachment_content_type`.

**Comment by amacou** [comment]
Hello,

thank you for your polite explanation.
unfortunately I can not use `validates_attachment_content_type` in my case.
because I want to accept gif file and then only exec thumbnail processor.

so, I will try making it myself by referring to your code.

**Comment by svoboda-jan** [comment]
If you need to conditionally run a processor you can define it with a lambda:

```ruby
class User < ActiveRecord::Base

  has_attached_file :image, :styles => {
    :tiny => {
      geometry: '190x190>',
      mozjpeg_options: '-quality 30', 
    },
    :large => {
      geometry: '1280x1280>',
      mozjpeg_options: '-quality 70 -quant-table 2 -notrellis',
    }
  },
  # processors: [ :thumbnail, :mozjpeg ]
  processors: -> (instance) { instance.asset_processors }
  
  def asset_processors
    unless is_gif?
      [ :thumbnail, :mozjpeg ]
    else
      [ :thumbnail ]
    end
  end

  def is_gif?
    image.image_content_type == "image/gif"
  end

end
```

**Comment by amacou** [comment]
its good idea. thanks 👍

**Pull request closed without merging**
